global:
  resolve_timeout: 1m
  slack_api_url: <your slack API URL>

route:
  receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#prometheus-alert"
        send_resolved: true
