route:
  receiver: "mail"
  repeat_interval: 1m
  group_by: [alertname]

receivers:
  - name: "mail"
    email_configs:
      - smarthost: "smtp-relay.gmail.com:587"
        auth_username: ${TEST_EMAIL}
        auth_password: ${TEST_EMAIL_APP_PW}
        from: ${TEST_EMAIL}
        to: ${TEST_EMAIL_RCVR}
