version: '3.8'
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker-1
    ports:
      - 2376:2376
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - 'jenkins-docker-certs:/certs/client'
      - 'jenkins-data:/var/jenkins_home'

  jenkins-blueocean:
    build:
      context: jenkins
      dockerfile: Dockerfile
    image: myjenkins-blueocean:2.401.2-1
    container_name: jenkins-blueocean-1
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    restart: on-failure
    networks:
      - jenkins

  docker-proxy:
    image: shipyard/docker-proxy
    container_name: docker-proxy-1
    ports: 
      - '3375:2375'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  agent:
    image: jenkins/ssh-agent:jdk11
    container_name: agent-1
    expose:
      - 22
    networks:
      - jenkins    
    privileged: true
    user: root
    env_file: .env
    # the .env file contains the variable JENKINS_AGENT_SSH_PUBKEY

  prometheus:
    image: prom/prometheus
    container_name: prometheus-1
    ports:
      - 9090:9090
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus_data:/prometheus'

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-1
    ports: 
      - 3000:3000
    volumes:
      - 'grafana_storage:/var/lib/grafana'
      - 'grafana_ini:/etc/grafana'
    environment:
        - GF_RENDERING_SERVER_URL=http://renderer:8081/render
        - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
        - GF_LOG_FILTERS=rendering:debug
    #   - 'GF_SMTP_ENABLED=true'
    #   - 'GF_SMTP_HOST=smtp.gmail.com:587'
    #   - 'GF_SMTP_USER=<email>@gmail.com'
    #   - 'GF_SMTP_PASSWORD=<password>' #might require App Password for Gmail
    #   - 'GF_SMTP_FROM_ADDRESS=<email>@gmail.com'
    #   - 'GF_SMTP_FROM_NAME=grafana'
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer-1
    ports:
      - 8081

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
  grafana_storage: {}
  grafana_ini: {}
  prometheus_data:
  # prometheus-config:
  #   type: volume
  #   device: "./prometheus/prometheus.yml"
    # source: ./prometheus/prometheus.yml
    # target: /etc/prometheus/prometheus.yml